services:
 www:
  build: .
  ports: 
   - "80:80"
  volumes:
   - ./www:/var/www/html/
  links:
   - db
 db:
  image: mysql:5.7
  ports: 
   - "3310:3306"
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_DATABASE: apache_docker_db
   MYSQL_ROOT_PASSWORD: root 
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links: 
   - db:db
  ports:
   - 8010:80
  environment:
   MYSQL_USER: root
   MYSQL_ROOT_PASSWORD: root 